---

- name: Die externe Festplatte geht nicht wenn man das nicht anpasst
  lineinfile: dest=/boot/config.txt regexp="^max_usb_current" line="max_usb_current=1"

- name: etckeeper commit
  shell: cd /etc/ && git diff-index --quiet HEAD || etckeeper commit "ansible osmc-config commit state."
