---


- name: Update all packages to the latest version
  apt: upgrade=dist cache_valid_time=3600
  tags: update-packages

- name: etckeeper commit
  shell: cd /etc/ && git diff-index --quiet HEAD || etckeeper commit "ansible update-packages commit state."

