---

# *****************
# * user puchrojo *
# *****************
# Doku: https://serversforhackers.com/an-ansible-tutorial
#       http://docs.ansible.com/ansible/authorized_key_module.html
#password={% verbatim %}{{ puchrojo_password }}{% endverbatim %}
# Was verbatim ist habe ich nicht rausgefunden und hat Fehler gemacht

- name: Add Gruppe puchrojo
  group: name=feder gid=1048 state=present
  tags: test253  

- name: Add Benutzer puchrojo, zum testen
  #     #password={{puchrojo_password}} # weglelasen um es einfach zu machen. Key oder nichts. 
  user:
    name=puchrojo
    groups=sudo
    append=yes
    shell=/bin/bash
    uid=1048
  tags: users
    
- name: Add Authorized Key
  authorized_key:
    user=puchrojo
    key=https://github.com/puchrojo.keys
    state=present
  tags: users

- name: Add .bash_aliases für puchrojo
  copy: src=bash_aliases_klein dest=/home/puchrojo/.bash_aliases
        owner=puchrojo group=puchrojo mode=0640
  tags: test2

- name: Add .bash_aliases für root
  copy: src=bash_aliases_klein dest=/root/.bash_aliases
        owner=root group=root mode=0640
  tags: test2

- name: aktivieren .bash_aliases für root
  lineinfile: dest=/root/.bashrc regexp="^source ~/.bash_aliases" line="source ~/.bash_aliases"
  tags: test2
   
- name: script version
  copy: src=/usr/local/bin/feder/version dest=/usr/local/bin/version mode=0755
  tags: version

- name: Delte standard Password für osmc (nur Debian/OSMC)
  shell: passwd osmc -d
  ignore_errors: True

- name: Delte standard Password für ubuntu (nur Ubuntu)
  shell: passwd ubuntu -d
  ignore_errors: True
